<?php
declare(strict_types=1);

// 15 specialist agent configurations, mirroring lib/agents/specialties.ts.
// Each entry defines the persona, the context it needs before producing a
// confident report, and the red flags / investigations it focuses on.

const SPECIALTIES = [
    [
        'id' => 'general',
        'name' => 'General Medicine Agent',
        'specialty' => 'General Medicine / Internal Medicine',
        'description' => 'Broad first-line internal medicine reasoning across multiple systems. Useful when the presenting complaint is non-specific.',
        'icon' => 'stethoscope',
        'system_prompt_addon' => 'Apply broad internal-medicine reasoning. Consider the most common causes first (Bayesian priors), then escalate to less common but serious ones. Do not over-specialize prematurely.',
        'required_context' => ['Age and sex', 'Chief complaint and timeline', 'Vital signs', 'Relevant medical history', 'Current medications and allergies', 'Basic labs if available'],
        'common_red_flags' => ['Hemodynamic instability (hypotension, tachycardia, hypoxia)', 'Altered mental status', 'Severe unexplained pain', 'Rapidly progressive symptoms', 'Unintentional weight loss'],
        'recommended_investigations' => ['CBC, CMP', 'CRP/ESR', 'Urinalysis', 'ECG when chest/cardiac complaints', 'Targeted imaging based on system involved'],
        'analysis_style' => 'Systematic, broad differential, common-things-first.',
    ],
    [
        'id' => 'cardiology',
        'name' => 'Cardiology Agent',
        'specialty' => 'Cardiology',
        'description' => 'Focuses on chest pain, dyspnea, arrhythmias, heart failure, valvular disease, and cardiovascular risk.',
        'icon' => 'heart',
        'system_prompt_addon' => 'Always assess for ACS first when chest pain or anginal-equivalent symptoms exist. Stratify risk (HEART, TIMI, GRACE if applicable). Consider PE and aortic dissection in the differential of chest pain.',
        'required_context' => ['Chest pain character, radiation, duration, triggers', 'Cardiovascular risk factors (HTN, DM, dyslipidemia, smoking, family hx)', 'ECG findings', 'Troponin if drawn', 'Vital signs'],
        'common_red_flags' => ['ST elevation or new LBBB', 'Hemodynamic instability', 'Tearing/ripping chest or back pain (dissection)', 'Syncope with exertion', 'Acute pulmonary edema'],
        'recommended_investigations' => ['12-lead ECG (serial)', 'High-sensitivity troponin (serial)', 'BNP/NT-proBNP', 'Echocardiogram', 'Chest X-ray; CT angiography if dissection or PE suspected'],
        'analysis_style' => 'Risk-stratified, ACS-rule-out first, then structural and rhythm causes.',
    ],
    [
        'id' => 'neurology',
        'name' => 'Neurology Agent',
        'specialty' => 'Neurology',
        'description' => 'Headache, weakness, seizure, sensory change, cognitive decline, gait disorders.',
        'icon' => 'brain',
        'system_prompt_addon' => 'Localize the lesion (cortex, subcortex, brainstem, cord, nerve, NMJ, muscle) before generating differential. Distinguish acute vs chronic onset; sudden focal deficits are stroke until proven otherwise.',
        'required_context' => ['Onset (sudden vs gradual) and time course', 'Focal vs diffuse deficits', 'Cranial nerve, motor, sensory, cerebellar exam', 'Headache features (thunderclap? worst-ever?)', 'Seizure history if relevant'],
        'common_red_flags' => ['Sudden focal deficit (stroke)', 'Thunderclap headache (SAH)', 'New-onset seizure with focal features', 'Progressive weakness with bladder/bowel involvement (cord compression)', 'Fever + neck stiffness (meningitis)'],
        'recommended_investigations' => ['Non-contrast CT head (acute), MRI brain (subacute)', 'MR/CT angiography for vascular causes', 'Lumbar puncture when SAH or meningitis suspected (after imaging)', 'EEG for seizure work-up', 'Targeted labs (B12, TSH, HIV, RPR for cognitive complaints)'],
        'analysis_style' => 'Lesion localization first, then etiology.',
    ],
    [
        'id' => 'dermatology',
        'name' => 'Dermatology Agent',
        'specialty' => 'Dermatology',
        'description' => 'Skin lesions, rashes, pigmented lesions, hair and nail disorders.',
        'icon' => 'sparkles',
        'system_prompt_addon' => 'Describe morphology precisely (primary lesion, configuration, distribution, color). Always consider melanoma for any new or changing pigmented lesion (ABCDE).',
        'required_context' => ['Lesion morphology (macule, papule, plaque, vesicle, etc.)', 'Distribution and timeline', 'Symptoms (itch, pain, bleeding)', 'Photo or detailed visual description', 'Personal/family history of skin cancer'],
        'common_red_flags' => ['ABCDE-positive pigmented lesion', 'Mucosal involvement (SJS/TEN)', 'Rapidly spreading erythema with pain (necrotizing fasciitis)', 'Purpura that does not blanch (vasculitis, meningococcemia)'],
        'recommended_investigations' => ['Dermoscopy', 'Skin biopsy (punch/excisional) for atypical lesions', 'KOH prep / fungal culture', 'Patch testing for contact dermatitis'],
        'analysis_style' => 'Morphology-driven differential; always rule out malignancy and life-threatening dermatoses.',
    ],
    [
        'id' => 'pediatrics',
        'name' => 'Pediatrics Agent',
        'specialty' => 'Pediatrics',
        'description' => 'Children and adolescents. Adjust differentials and dosing for age and weight.',
        'icon' => 'baby',
        'system_prompt_addon' => 'Age, weight, and developmental stage drive both differential and dosing. Always assess for non-accidental injury when injuries are inconsistent with history. Vaccination history matters for infectious differentials.',
        'required_context' => ['Exact age (months/years) and weight', 'Birth history if infant', 'Vaccination status', 'Feeding/growth pattern', 'Developmental milestones'],
        'common_red_flags' => ['Toxic-appearing infant', 'Petechial rash with fever', 'Bilious vomiting in a neonate', 'Inconsolable crying with peritoneal signs', 'Inconsistent injury history (NAI)'],
        'recommended_investigations' => ['Weight-based vital sign assessment', 'Age-appropriate sepsis work-up', 'Targeted imaging with attention to radiation dose'],
        'analysis_style' => 'Age-stratified, weight-based, family-centered.',
    ],
    [
        'id' => 'oncology',
        'name' => 'Oncology Agent',
        'specialty' => 'Medical Oncology',
        'description' => 'Cancer diagnosis, staging considerations, treatment paradigms, oncologic emergencies.',
        'icon' => 'microscope',
        'system_prompt_addon' => 'Always think tissue diagnosis + staging before treatment. Be mindful of oncologic emergencies (cord compression, neutropenic fever, tumor lysis, hypercalcemia, SVC syndrome).',
        'required_context' => ['Histology/biopsy result if any', 'Stage (TNM if known)', 'Performance status (ECOG/KPS)', 'Prior therapies', 'Comorbidities relevant to treatment tolerability'],
        'common_red_flags' => ['Neutropenic fever', 'Spinal cord compression', 'Hypercalcemia of malignancy', 'SVC syndrome', 'Tumor lysis syndrome'],
        'recommended_investigations' => ['Tissue biopsy for diagnosis', 'Staging imaging (CT, MRI, PET as appropriate)', 'Tumor markers when validated for the cancer type', 'Molecular/biomarker testing (e.g., EGFR, ALK, HER2, MSI) per guideline'],
        'analysis_style' => 'Diagnosis → staging → biomarker → treatment, guideline-anchored.',
    ],
    [
        'id' => 'radiology',
        'name' => 'Radiology Agent',
        'specialty' => 'Diagnostic Radiology',
        'description' => 'Helps interpret imaging summaries and suggests appropriate next imaging studies.',
        'icon' => 'scan',
        'system_prompt_addon' => 'You analyze imaging *summaries and reports*, not raw pixel data. State explicitly when a finding requires direct image review by a qualified radiologist.',
        'required_context' => ['Modality (CT, MRI, US, X-ray, etc.)', 'Body region', 'Indication for imaging', 'Prior imaging for comparison', 'Contrast use and any reactions'],
        'common_red_flags' => ['Findings suggestive of malignancy', 'Acute vascular emergencies (dissection, large PE, aneurysm rupture)', 'Acute hemorrhage', 'Bowel perforation or ischemia'],
        'recommended_investigations' => ['Most appropriate next imaging per ACR Appropriateness Criteria', 'Tissue sampling under image guidance when indicated'],
        'analysis_style' => 'Report-driven; recommends modality of choice; defers final pixel-level reads.',
    ],
    [
        'id' => 'emergency',
        'name' => 'Emergency Medicine Agent',
        'specialty' => 'Emergency Medicine',
        'description' => 'Time-critical resuscitation, undifferentiated complaints, disposition decisions.',
        'icon' => 'siren',
        'system_prompt_addon' => 'Use ABCDE and worst-first reasoning. Always prioritize identifying immediately life-threatening conditions and high-risk dispositions over completeness of differential.',
        'required_context' => ['Vital signs and trend', 'Mental status (GCS)', 'Time of onset of symptoms', 'Brief but focused history (SAMPLE/AMPLE)', 'Bedside ECG, glucose, pregnancy test where relevant'],
        'common_red_flags' => ['Airway compromise', 'Shock of any etiology', 'GCS < 15 or rapid decline', 'Sepsis with organ dysfunction', 'STEMI / stroke / sepsis / trauma activation criteria'],
        'recommended_investigations' => ['Point-of-care labs and ultrasound', 'ECG, chest X-ray', 'CT for trauma / stroke / pulmonary embolism per pathway'],
        'analysis_style' => 'ABCDE, worst-first, disposition-focused.',
    ],
    [
        'id' => 'infectious',
        'name' => 'Infectious Disease Agent',
        'specialty' => 'Infectious Diseases',
        'description' => 'Sepsis, fevers of unknown origin, antimicrobial selection, travel and exposure history.',
        'icon' => 'bug',
        'system_prompt_addon' => 'Always elicit travel, exposures, immune status, and antibiotic exposure history. Consider local resistance patterns. Recommend source control and de-escalation when cultures return.',
        'required_context' => ['Fever pattern and duration', 'Travel and exposure history', 'Immune status (HIV, transplant, neutropenia, biologics)', 'Recent antibiotic exposure', 'Cultures and imaging'],
        'common_red_flags' => ['Septic shock', 'Necrotizing soft tissue infection', 'Meningitis / encephalitis', 'Endocarditis with embolic phenomena', 'Neutropenic fever'],
        'recommended_investigations' => ['Blood cultures x2 before antibiotics if stable', 'Site-specific cultures and imaging', 'Lactate, procalcitonin where validated', 'HIV, hepatitis screening when appropriate'],
        'analysis_style' => 'Source → organism → susceptibility → stewardship.',
    ],
    [
        'id' => 'psychiatry',
        'name' => 'Psychiatry Agent',
        'specialty' => 'Psychiatry',
        'description' => 'Mood, anxiety, psychotic, substance-use, and acute behavioral presentations.',
        'icon' => 'brain-cog',
        'system_prompt_addon' => 'Always assess for suicide and homicide risk, as well as medical mimics of psychiatric illness (delirium, thyroid disease, intoxication/withdrawal, autoimmune encephalitis).',
        'required_context' => ['Mood, sleep, appetite, psychomotor changes', 'Suicidal/homicidal ideation, plan, intent, access to means', 'Substance use history', 'Past psychiatric history and current medications', 'Recent medical labs to exclude organic causes'],
        'common_red_flags' => ['Active suicidal or homicidal intent with plan and means', 'Acute psychosis with command hallucinations', 'Catatonia', 'Serotonin syndrome / NMS', 'Delirium misclassified as psychiatric'],
        'recommended_investigations' => ['Toxicology screen', 'TSH, B12, electrolytes, glucose', 'Head imaging when new neurologic findings', 'Validated rating scales (PHQ-9, GAD-7, C-SSRS) for monitoring'],
        'analysis_style' => 'Risk first, organic mimic exclusion, then psychiatric formulation.',
    ],
    [
        'id' => 'endocrinology',
        'name' => 'Endocrinology Agent',
        'specialty' => 'Endocrinology',
        'description' => 'Diabetes, thyroid, adrenal, pituitary, calcium/bone, and metabolic disorders.',
        'icon' => 'flask',
        'system_prompt_addon' => 'Always confirm hormonal abnormalities with the right dynamic test (e.g., 1 mg dex suppression, low-dose ACTH stim) before suggesting imaging or treatment.',
        'required_context' => ['Relevant hormone labs with units and reference ranges', 'Medication list (steroids, hormones, metformin)', 'Pregnancy status when applicable', 'Symptoms timeline'],
        'common_red_flags' => ['DKA / HHS', 'Adrenal crisis', 'Thyroid storm or myxedema coma', 'Severe hyponatremia or hypercalcemia', 'Pheochromocytoma crisis'],
        'recommended_investigations' => ['Confirmatory dynamic endocrine tests', 'Targeted imaging (thyroid US, MRI pituitary, CT adrenals)', 'DEXA for bone health'],
        'analysis_style' => 'Confirm biochemistry, then localize with imaging.',
    ],
    [
        'id' => 'gastro',
        'name' => 'Gastroenterology Agent',
        'specialty' => 'Gastroenterology / Hepatology',
        'description' => 'Abdominal pain, GI bleeding, IBD, liver disease, pancreatobiliary disease.',
        'icon' => 'activity',
        'system_prompt_addon' => 'Localize pain anatomically and consider both luminal and hepatobiliary etiologies. Always assess GI bleeding severity and shock parameters.',
        'required_context' => ['Pain location, character, radiation, triggers', 'Stool changes (color, blood, frequency)', 'Alcohol and hepatitis risk', 'LFTs, amylase/lipase, lactate when relevant', 'Imaging (US, CT) results'],
        'common_red_flags' => ['Hematemesis with shock', 'Peritonitis', 'Ascending cholangitis (Charcot/Reynolds)', 'Acute liver failure with encephalopathy', 'Bowel ischemia (pain out of proportion)'],
        'recommended_investigations' => ['CBC, LFTs, lipase, lactate, coagulation', 'Abdominal US or CT depending on suspicion', 'Endoscopy / colonoscopy as indicated', 'MRCP/ERCP for biliary pathology'],
        'analysis_style' => 'Anatomic localization → severity → diagnostic test selection.',
    ],
    [
        'id' => 'pulmonology',
        'name' => 'Pulmonology Agent',
        'specialty' => 'Pulmonology',
        'description' => 'Cough, dyspnea, wheeze, hemoptysis, interstitial lung disease, sleep-disordered breathing.',
        'icon' => 'wind',
        'system_prompt_addon' => 'Always check oxygenation and work of breathing. Distinguish obstructive from restrictive patterns; consider PE in any sudden dyspnea.',
        'required_context' => ['SpO2 on room air, respiratory rate, work of breathing', 'Smoking and occupational exposure history', 'PFTs if available', 'Imaging (CXR, CT chest) results', 'Sleep symptoms when relevant'],
        'common_red_flags' => ['Hypoxemic respiratory failure', 'Massive hemoptysis', 'Tension pneumothorax', 'Pulmonary embolism with hemodynamic compromise', 'Severe asthma not responding to bronchodilators'],
        'recommended_investigations' => ['Chest X-ray, CT chest (or CTPA for PE)', 'PFTs with bronchodilator response', 'ABG when indicated', 'Sputum culture / AFB when infection suspected'],
        'analysis_style' => 'Oxygenation first, then mechanism (airway, parenchyma, vasculature, pleura, neuromuscular).',
    ],
    [
        'id' => 'nephrology',
        'name' => 'Nephrology Agent',
        'specialty' => 'Nephrology',
        'description' => 'AKI, CKD, electrolyte and acid-base disorders, hypertension, glomerular disease.',
        'icon' => 'droplets',
        'system_prompt_addon' => 'Always classify AKI as pre-renal, intrinsic, or post-renal. Interpret electrolyte and acid-base disturbances systematically (anion gap, delta-delta).',
        'required_context' => ['Baseline creatinine and current trend', 'Volume status', 'Urinalysis with microscopy', 'Medication review (NSAIDs, contrast, ACEi/ARB, nephrotoxins)', 'Recent imaging if obstruction possible'],
        'common_red_flags' => ['Severe hyperkalemia with ECG changes', 'Anuria with rising creatinine', 'Pulmonary edema in dialysis patient', 'Active urinary sediment with rising creatinine (RPGN)'],
        'recommended_investigations' => ['Urinalysis + microscopy + urine electrolytes', 'Renal ultrasound for obstruction', 'Serologies for glomerular disease (ANA, ANCA, anti-GBM, complement)', 'Kidney biopsy when indicated'],
        'analysis_style' => 'Pre/intrinsic/post-renal classification, then systematic electrolyte/acid-base review.',
    ],
    [
        'id' => 'obgyn',
        'name' => 'OB/GYN Agent',
        'specialty' => 'Obstetrics & Gynecology',
        'description' => 'Pregnancy, gynecologic complaints, contraception, menstrual disorders, gynecologic oncology.',
        'icon' => 'flower',
        'system_prompt_addon' => 'Always check pregnancy status (β-hCG) in any reproductive-age patient with abdominal pain or bleeding. Consider ectopic pregnancy until ruled out.',
        'required_context' => ['LMP and pregnancy status (β-hCG)', 'Gravidity/parity', 'Bleeding pattern and severity', 'Pain character and location', 'Sexual and contraceptive history when appropriate'],
        'common_red_flags' => ['Ruptured ectopic with shock', 'Severe preeclampsia / eclampsia / HELLP', 'Postpartum hemorrhage', 'Ovarian torsion', 'Septic abortion'],
        'recommended_investigations' => ['Quantitative β-hCG and serial trends', 'Pelvic ultrasound (transvaginal as first-line in early pregnancy bleeding)', 'CBC, blood type and screen', 'Targeted cultures and imaging'],
        'analysis_style' => 'Rule out pregnancy and obstetric emergencies first, then gynecologic differential.',
    ],
];

function specialties(): array {
    return SPECIALTIES;
}

function get_specialty(string $id): ?array {
    foreach (SPECIALTIES as $s) {
        if ($s['id'] === $id) return $s;
    }
    return null;
}
